add experiment settings
SecurityLab-UCD/AgentBench pull request #3
Opened 2024-03-13 01:46 UTC by StupiddCupid

2024-03-13 01:47 UTC, EYH0602 requested changes

2024-03-13 01:47 UTC, EYH0602 commented on configs/assignments/default.yaml
> +    Llama-2-7b:5
we are using vicuna-7b now

2024-05-30 19:09 UTC, EYH0602 requested changes

2024-05-30 19:09 UTC, EYH0602 commented on data/os_interaction/data/6/avalibillity.json
> +
this file is empty?

2024-05-30 19:13 UTC, StupiddCupid commented
Forgot to upload it. Already fixed it.

On Thu, May 30, 2024 at 12:09 Yifeng He ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In data/os_interaction/data/6/avalibillity.json
> <https://github.com/SecurityLab-UCD/AgentBench/pull/3#discussion_r1621084108>
> :
>
> > @@ -0,0 +1 @@
> +
>
> this file is empty?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SecurityLab-UCD/AgentBench/pull/3#pullrequestreview-2088849417>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2LG2JKO2GWJMCQIZBC2ERTZE52PZAVCNFSM6AAAAABETIPXDCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOBYHA2DSNBRG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-31 00:07 UTC, EYH0602 commented on configs/agents/fs_agent.yaml
> +    model_name: "Llama-2-7b-chat-hf"
do we still need config for Llama?

2024-05-31 00:10 UTC, StupiddCupid commented on configs/agents/fs_agent.yaml
> +    model_name: "Llama-2-7b-chat-hf"
Nope. Switched to use gpt3.5 instead.

2024-05-31 16:45 UTC, EYH0602 commented on configs/agents/fs_agent.yaml
> +    model_name: "Llama-2-7b-chat-hf"
then you can remove this

2024-05-31 16:47 UTC, StupiddCupid commented
ok！

On Fri, May 31, 2024 at 09:45 Yifeng He ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In configs/agents/fs_agent.yaml
> <https://github.com/SecurityLab-UCD/AgentBench/pull/3#discussion_r1622697596>
> :
>
> >      max_new_tokens: 512
>      temperature: 0
>
> +llama-2-70b:
> +  parameters:
> +    model_name: "Llama-2-70b-v0"
> +
> +llama-2-7b:
> +  parameters:
> +    model_name: "Llama-2-7b-chat-hf"
>
> then you can remove this
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SecurityLab-UCD/AgentBench/pull/3#discussion_r1622697596>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2LG2JNPTYOSN7GRYPJWKEDZFCSL7AVCNFSM6AAAAABETIPXDCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAOJRGI4TIOBYGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-01 04:39 UTC, EYH0602 approved these changes

2024-08-06 21:24 UTC, merged